services:
  postgres:
    image: postgres:13
    container_name: virtubuildpostgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $APP_DB_USERNAME
      POSTGRES_PASSWORD: $APP_DB_PASSWORD
      POSTGRES_DB: $APP_DB_DATABASE
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: virtubuildnodeapp
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
